"""attribute fix

Revision ID: 8a29fe1398c0
Revises: 86d0e3f0f2d3
Create Date: 2024-06-12 07:45:25.582818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a29fe1398c0'
down_revision = '86d0e3f0f2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.drop_column('iamge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iamge', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
